---
label: default
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: ''
- name: keywords
  label: Keywords
  type: text
  hidden: false
  default: ''
- name: description
  label: Description
  type: text
  hidden: false
  default: ''
- name: banner
  label: Banner
  type: file
  hidden: false
  default: "/images/default_banner.jpg"
pages:
- content/career.md
- content/faq.md
- content/newsletter.md
